default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  username: rultor
  password: rultor

test:
  <<: *default
  username: rultor
  password: rultor

production:
  <<: *default
  <% if Rails.application.secrets[:pgsql].present? %>
    host: <%= Rails.application.secrets[:pgsql][:url]%>
    username: <%= Rails.application.secrets[:pgsql][:user]%>
    password: <%= Rails.application.secrets[:pgsql][:password]%>
  <% end %>